version: "3.9"
services:  
  client:
    container_name: client_sigcli
    image: client_sigcli_image
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app/client
    
  server:
    container_name: server_sigcli_container
    image: server_sigcli_image
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app/server

